service: video-cognito

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}
  timeout: 30
  profile: ${opt:profile, "nadtakan"}
  
resources:
  # AWS Resources
  Resources: ${file(./resources/general.yml)}
  Outputs: ${file(./resources/general-outputs.yml)}

  